### ISSUE TITLE
tasks missing?

### ISSUE THREAD

**Issue by geftactics** [trainline-eu/dovico#18]
My API connectivity is working ok...

```
gkendal@5005331:~$ dovico --myself
Informations about yourself
 - ID:         3240
 - First Name: Geoff
 - Last Name:  Kendal
```

But whenever I'm interacting with the actual projects etc...

```
gkendal@5005331:~$ dovico --show --start 2019-09-16 --end 2019-09-19
== List of Time Entries between 2019-09-16 and 2019-09-19 ==
Traceback (most recent call last):
	9: from /Users/gkendal/.rbenv/versions/2.6.3/bin/dovico:23:in `<main>'
	8: from /Users/gkendal/.rbenv/versions/2.6.3/bin/dovico:23:in `load'
	7: from /Users/gkendal/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dovico-1.4.0/bin/dovico:4:in `<top (required)>'
	6: from /Users/gkendal/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dovico-1.4.0/lib/dovico/app.rb:77:in `run'
	5: from /Users/gkendal/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dovico-1.4.0/lib/dovico/app.rb:123:in `display_time_entries'
	4: from /Users/gkendal/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dovico-1.4.0/lib/dovico/model/time_entry_formatter.rb:10:in `format_entries'
	3: from /Users/gkendal/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dovico-1.4.0/lib/dovico/model/time_entry_formatter.rb:10:in `map'
	2: from /Users/gkendal/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dovico-1.4.0/lib/dovico/model/time_entry_formatter.rb:12:in `block in format_entries'
	1: from /Users/gkendal/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dovico-1.4.0/lib/dovico/model/time_entry_formatter.rb:20:in `time_entry_text'
/Users/gkendal/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dovico-1.4.0/lib/dovico/model/time_entry_formatter.rb:36:in `project_task': undefined method `tasks' for nil:NilClass (NoMethodError)
```

I can list projects and tasks ok, but we seem to have an additional level under here which seems to be missing from when I'm trying to interact with them... Any advice?

**Comment by chtitux** [comment]
It seems it's because here, you have an assignment with a `project_id` that is not listed in the `projects_search = ApiClient.get(URL_PATH)` call:

```ruby
    def project_task(project_id, task_id)
      project = projects.select{ |project| project.id == project_id }.first
      task = project.tasks.select{ |task| task.id == task_id }.first

      [project, task]
    end
```

If you want to help us to debug, you could:
1. Edit ` /Users/gkendal/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dovico-1.4.0/lib/dovico/model/time_entry_formatter.rb` and add after line 19 and before line 20: `      puts "TE.p_id=#{time_entry.project_id}, TE.t_id=#{time_entry.task_id}"`
2. The result of ` dovico --show --start 2019-09-16 --end 2019-09-19`
3. The result of `dovico --tasks` (you can remove the text, just keep IDs)

An another cause could be you have too many assignments and the gem does not support pagination.

**Comment by geftactics** [comment]
Sorry for delay in coming back on this one... I've updated `time_entry_formatter.rb` as described...

```
gkendal@5005331:~$ dovico --show --start 2019-09-16 --end 2019-09-19
== List of Time Entries between 2019-09-16 and 2019-09-19 ==
TE.p_id=3827, TE.t_id=249
Traceback (most recent call last):
	9: from /Users/gkendal/.rbenv/versions/2.6.3/bin/dovico:23:in `<main>'
	8: from /Users/gkendal/.rbenv/versions/2.6.3/bin/dovico:23:in `load'
	7: from /Users/gkendal/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dovico-1.4.0/bin/dovico:4:in `<top (required)>'
	6: from /Users/gkendal/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dovico-1.4.0/lib/dovico/app.rb:77:in `run'
	5: from /Users/gkendal/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dovico-1.4.0/lib/dovico/app.rb:123:in `display_time_entries'
	4: from /Users/gkendal/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dovico-1.4.0/lib/dovico/model/time_entry_formatter.rb:10:in `format_entries'
	3: from /Users/gkendal/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dovico-1.4.0/lib/dovico/model/time_entry_formatter.rb:10:in `map'
	2: from /Users/gkendal/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dovico-1.4.0/lib/dovico/model/time_entry_formatter.rb:12:in `block in format_entries'
	1: from /Users/gkendal/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dovico-1.4.0/lib/dovico/model/time_entry_formatter.rb:21:in `time_entry_text'
/Users/gkendal/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dovico-1.4.0/lib/dovico/model/time_entry_formatter.rb:37:in `project_task': undefined method `tasks' for nil:NilClass (NoMethodError)
```

If I run `dovico --tasks` I get around 2000 rows returned, of the format:

`165 | 3821 | Group Projects - Archive: 2018 - Shared Services - foobar project `

Hope this helps in some way!

**Comment by geftactics** [comment]
Hiya, was the above of any use? Let me know if there is anything else I can do to help!

**Comment by chtitux** [comment]
>  I get around 2000 rows returned

I think it's the issue : the pagination is not implemented yet and you'll have an assignment outside the first page of the list of assignments.

I have opened a dedicated issue #19 to track implementation.

**Comment by squiggleuk** [comment]
Tried building from the PR (I did `make build`, then `gem install dovico*.gem` - I think that's right?)

Got the following when I tried the same command as above...

`
14:56 $ dovico --show --start 2019-09-16 --end 2019-09-19
== List of Time Entries between 2019-09-16 and 2019-09-19 ==
== Error during HTTP request ==
Status:      BadRequest
Description: Please specify the "version" value in the correct numeric format.

Traceback (most recent call last):
	10: from /Users/gkendal/.rbenv/versions/2.6.5/bin/dovico:23:in `<main>'
	 9: from /Users/gkendal/.rbenv/versions/2.6.5/bin/dovico:23:in `load'
	 8: from /Users/gkendal/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dovico-1.4.0/bin/dovico:4:in `<top (required)>'
	 7: from /Users/gkendal/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dovico-1.4.0/lib/dovico/app.rb:77:in `run'
	 6: from /Users/gkendal/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dovico-1.4.0/lib/dovico/app.rb:122:in `display_time_entries'
	 5: from /Users/gkendal/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dovico-1.4.0/lib/dovico/model/time_entry.rb:43:in `search'
	 4: from /Users/gkendal/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dovico-1.4.0/lib/dovico/api_client.rb:36:in `get_paginated_list'
	 3: from /Users/gkendal/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dovico-1.4.0/lib/dovico/api_client.rb:36:in `loop'
	 2: from /Users/gkendal/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dovico-1.4.0/lib/dovico/api_client.rb:40:in `block in get_paginated_list'
	 1: from /Users/gkendal/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dovico-1.4.0/lib/dovico/api_client.rb:17:in `get'
/Users/gkendal/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dovico-1.4.0/lib/dovico/api_client.rb:86:in `perform!': Error during HTTP request (RuntimeError)
`
